# Debian 12 (Bookworm) image to build binary for distroless/static-debian12
FROM golang:1.26.5-bookworm@sha256:1ecb7edf62a0408027bd5729dfd6b1b8766e578e8df93995b225dfd0944eb651 AS build

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN CGO_ENABLED=0 go build -v -o ./witness-server ./cmd/witness-server

FROM gcr.io/distroless/static-debian12:nonroot@sha256:f5b485ea962d9bd1186b2f6b3a061191539b905b82ec395de78cbfae51f20e35 AS deploy

COPY --from=build /build/witness-server /usr/local/bin/witness-server

ENTRYPOINT ["witness-server"]
