FROM golang:1.26.5@sha256:3aff6657219a4d9c14e27fb1d8976c49c29fddb70ba835014f477e1c70636647 AS build

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN CGO_ENABLED=0 go build -v -o ./gen-key ./cmd/gen-key

FROM golang:1.26.5@sha256:3aff6657219a4d9c14e27fb1d8976c49c29fddb70ba835014f477e1c70636647 

WORKDIR /home/app

COPY --from=build /build/gen-key ./

ENTRYPOINT ["./gen-key"]
CMD ["--origin=binarytransparency.log/example", "--private-key-path=/home/app/keys/private.key", "--public-key-path=/home/app/keys/public.key"]
