FROM golang:1.25.2@sha256:1c91b4f4391774a73d6489576878ad3ff3161ebc8c78466ec26e83474855bfcf AS build

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN CGO_ENABLED=0 go build -v -o ./gen-key ./cmd/gen-key

FROM golang:1.25.2@sha256:1c91b4f4391774a73d6489576878ad3ff3161ebc8c78466ec26e83474855bfcf 

WORKDIR /home/app

COPY --from=build /build/gen-key ./

ENTRYPOINT ["./gen-key"]
CMD ["--origin=binarytransparency.log/example", "--private-key-path=/home/app/keys/private.key", "--public-key-path=/home/app/keys/public.key"]
