FROM golang:1.26.5@sha256:3aff6657219a4d9c14e27fb1d8976c49c29fddb70ba835014f477e1c70636647 AS build

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN CGO_ENABLED=0 go build -v -o ./witness-add-key ./cmd/witness-add-key

FROM golang:1.26.5@sha256:3aff6657219a4d9c14e27fb1d8976c49c29fddb70ba835014f477e1c70636647

WORKDIR /home/app

RUN apt-get update -y
RUN apt-get install -y sqlite3

RUN mkdir witness
RUN sqlite3 -line witness/witness.db '.database'

COPY --from=build /build/witness-add-key ./

ENTRYPOINT ["./witness-add-key"]
CMD ["--database-path=/home/app/witness/witness.db", "--public-key=/home/app/keys/public.key"]
