name: End-to-end Witness Database Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  e2e-databse-tests:
    name: End-to-end test with ${{ matrix.db }} witness backend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        db: [sqlite, mysql, postgres]

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: go.mod

    - name: Build docker images
      run: docker compose -f deploy/docker-compose.yml --profile admin --profile ${{ matrix.db }} build

    - name: Generate log and witness keys
      run: |
        docker compose -f deploy/docker-compose.yml run gen-key-log
        docker compose -f deploy/docker-compose.yml run gen-key-witness

    - name: Start services
      run: docker compose -f deploy/docker-compose.yml --profile ${{ matrix.db }} up --wait

    - name: Verify upload and checkpoint
      run: |
        curl -XPOST http://localhost:8080/add -d "{\"checksum\":\"sha256:5141b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be92\",\"filename\":\"pkgname-1.2.3-py3-none-any.whl\"}" -o bundle
        cat bundle
        cat bundle| jq -r .checkpoint | base64 -d
        index=$(cat bundle | jq -r .index)
        if [ $index -ne 0 ]; then exit 1; else true; fi

    - name: Check container logs on failure
      if: failure()
      run: docker compose -f deploy/docker-compose.yml --profile ${{ matrix.db }} logs

    - name: Tear down services
      if: always()
      run: docker compose -f deploy/docker-compose.yml --profile ${{ matrix.db }} down --volumes --remove-orphans
